language: python
python:
  - "3.6"
  - "3.7"
install: true
script: true
deploy:
  provider: pypi
  user: maroshmka
  password:
    secure: "D/zs+CPqTWQmv/fbSk5iExUu3CUCy9Azr6bz9HrnJ/PKJEwV/8BxPAATP6eNTs4alo4Z5jnc4JECaW+ekgwQNqi+3ucYsnq/j0GemASL8seIszmTvgwfcKpbSGwYPav/zbTG8OrSlUDsniRh86bEXdIK6L26jb+WFTw/5NQy5OT9UJY7gj413fHVHe4dtkhRJZPICD8ZRmMZLjZdG5nTaX+S2T9NEcEdpDZ65Bo565irRtGTaIt3vxQhwn5p7G8xmZ0Az/wADEUpFPwiXzqvRijuizFlM3WuNkOwYa0Ic6aPLEa3j3oH1cB1nlnlSFqzgw9W6plbYHaCcBPT/bP2moFzS+IIEKzpHaEzqsYJ3/eDVbJTELt7B+ycOORumJKL1wR/oxHHfr1vz8K0Jb+yWKiO6nxu/t7EaUbO0d8oexDJ4iHIRIsYT5YotUBr+T3ztIQuwcXo5vSF0+xj/we53rTGBEjQPtvYNKnS5MU+lmImLqbgfmiGoiCNeg0mgq2SSN6My7hgF9i57VaVpornAOwSqezrukDrlHbsf2tnXxj/dZEPavbCWbF8MXVl+MvUg3Ktjf1FU96apv94SpmYoLI1JyrZ6KMaZ49G0gprFipbrTKV7y7Q24A8I0YEzWAwJdV1gCmMS0EO5cLgGB6Vwe/qBtZIrACQrzoa8GCUmfs="
  on:
    tags: true
  distributions: sdist bdist_wheel
